version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    ports:
      - "0.0.0.0:9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./data:/usr/share/elasticsearch/data"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    ports:
      - "0.0.0.0:5601:5601"
networks:
  default:
    name: my-data-network
